import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Building2, CheckCircle2, CreditCard, Database, Pencil, Plus, Save, Settings, SlidersHorizontal, UserCog, Wrench } from "lucide-react";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { toast } from "sonner";
import { InternalPage, SectionPanel, StatusPill } from "@/components/InternalPage";
import { PageHeader } from "@/components/ui-helpers";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { useAuth } from "@/auth/AuthContext";
import { jaguarApi } from "@/services/jaguarApi";
import type { ApiUser, ServiceApi } from "@/types/api";
import { asNumber, dateTimePt } from "@/utils/api-format";
import { brl } from "@/utils/format";

export const Route = createFileRoute("/configuracoes")({ component: SettingsPage });

type CompanyForm={businessName:string;tradeName:string;cnpj:string;stateRegistration:string;phone:string;whatsapp:string;email:string;street:string;number:string;complement:string;neighborhood:string;city:string;state:string;postalCode:string;pixKeyType:string;pixKey:string;pixReceiverName:string;pixReceiverCity:string;reserveStockOnQuote:boolean;consumeStockOnComplete:boolean;defaultAuthorizationMethod:string};
const emptyCompany:CompanyForm={businessName:"Jaguar Radiadores",tradeName:"Jaguar Radiadores",cnpj:"",stateRegistration:"",phone:"",whatsapp:"",email:"",street:"",number:"",complement:"",neighborhood:"",city:"",state:"PR",postalCode:"",pixKeyType:"cnpj",pixKey:"",pixReceiverName:"Jaguar Radiadores",pixReceiverCity:"",reserveStockOnQuote:true,consumeStockOnComplete:true,defaultAuthorizationMethod:"verbal"};

function SettingsPage(){
  const {session}=useAuth(); const isAdmin=String(session?.user.role||"").toLowerCase()==="admin"; const qc=useQueryClient();
  const settings=useQuery({queryKey:["settings"],queryFn:jaguarApi.settings.get}); const services=useQuery({queryKey:["services"],queryFn:()=>jaguarApi.catalog.services()}); const health=useQuery({queryKey:["health"],queryFn:jaguarApi.health,refetchInterval:60000}); const users=useQuery({queryKey:["users"],queryFn:jaguarApi.settings.users,enabled:isAdmin});
  const [form,setForm]=useState<CompanyForm>(emptyCompany);
  useEffect(()=>{if(settings.data?.company)setForm(fromCompany(settings.data.company))},[settings.data]);
  const save=useMutation({mutationFn:()=>jaguarApi.settings.save(form),onSuccess:async()=>{toast.success("Configurações salvas no PostgreSQL.");await qc.invalidateQueries({queryKey:["settings"]})},onError:e=>toast.error(e.message)});
  async function refreshCatalog(){await Promise.all([qc.invalidateQueries({queryKey:["services"]}),qc.invalidateQueries({queryKey:["catalog"]})])}
  async function refreshUsers(){await qc.invalidateQueries({queryKey:["users"]})}
  return <InternalPage>
    <PageHeader title="Configurações" subtitle="Empresa, PIX, regras operacionais, serviços, usuários e saúde do backend Jaguar." icon={Settings} right={<Button onClick={()=>save.mutate()} disabled={!isAdmin||save.isPending}><Save className="mr-2 h-4 w-4"/>{save.isPending?"Salvando...":"Salvar alterações"}</Button>}/>
    <div className="grid gap-4 xl:grid-cols-2">
      <SectionPanel title="Dados da empresa" subtitle="Dados oficiais reutilizados nos documentos e cobranças" icon={Building2}>
        <div className="form-grid"><Field label="Razão social / nome"><Input value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})}/></Field><Field label="Nome fantasia"><Input value={form.tradeName} onChange={e=>setForm({...form,tradeName:e.target.value})}/></Field><Field label="CNPJ"><Input value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/></Field><Field label="Inscrição estadual"><Input value={form.stateRegistration} onChange={e=>setForm({...form,stateRegistration:e.target.value})}/></Field><Field label="Telefone"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="WhatsApp"><Input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></Field><label className="form-field xl:col-span-2"><span>E-mail</span><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-field xl:col-span-2"><span>Endereço</span><Input value={form.street} onChange={e=>setForm({...form,street:e.target.value})}/></label><Field label="Número"><Input value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></Field><Field label="Bairro"><Input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></Field><Field label="Cidade"><Input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field><Field label="UF"><Input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></Field></div>
      </SectionPanel>
      <SectionPanel title="PIX e formas de pagamento" subtitle="PIX usado no documento do orçamento; demais formas vêm do catálogo PostgreSQL" icon={CreditCard}>
        <div className="form-grid"><Field label="Tipo da chave PIX"><select className="h-10 rounded-md border border-input bg-background px-3" value={form.pixKeyType} onChange={e=>setForm({...form,pixKeyType:e.target.value})}><option value="cpf">CPF</option><option value="cnpj">CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Aleatória</option></select></Field><Field label="Chave PIX"><Input value={form.pixKey} onChange={e=>setForm({...form,pixKey:e.target.value})}/></Field><Field label="Nome do recebedor"><Input value={form.pixReceiverName} onChange={e=>setForm({...form,pixReceiverName:e.target.value})}/></Field><Field label="Cidade do recebedor"><Input value={form.pixReceiverCity} onChange={e=>setForm({...form,pixReceiverCity:e.target.value})}/></Field></div>
        <div className="mt-4 flex flex-wrap gap-2">{settings.data?.paymentMethods.map(m=><StatusPill key={m.code} label={m.name} tone="info"/>)}</div>
      </SectionPanel>
      <SectionPanel title="Preferências operacionais" subtitle="Regras executadas no backend, não apenas na interface" icon={SlidersHorizontal}>
        <div className="settings-lines"><div><span><b>Reservar estoque ao criar atendimento</b><small>Peças do orçamento ficam indisponíveis para outro atendimento.</small></span><Switch checked={form.reserveStockOnQuote} onCheckedChange={v=>setForm({...form,reserveStockOnQuote:v})}/></div><div><span><b>Dar baixa na conclusão</b><small>Consome as reservas quando o atendimento é concluído.</small></span><Switch checked={form.consumeStockOnComplete} onCheckedChange={v=>setForm({...form,consumeStockOnComplete:v})}/></div><div><span><b>Autorização padrão</b><small>O status continua simples: em andamento, concluído ou cancelado.</small></span><select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={form.defaultAuthorizationMethod} onChange={e=>setForm({...form,defaultAuthorizationMethod:e.target.value})}><option value="verbal">Verbal</option><option value="whatsapp">WhatsApp</option><option value="signature">Assinatura</option><option value="other">Outro</option></select></div></div>
      </SectionPanel>
      <SectionPanel title="Backend e banco" subtitle="Conectividade do frontend/server com n8n e PostgreSQL" icon={Database}>
        <div className="record-card"><div><b>API Jaguar</b><span>{health.isLoading?"Verificando...":health.data?.ok?"Online e conectada":"Indisponível"}</span></div><StatusPill label={health.data?.ok?"Online":"Offline"} tone={health.data?.ok?"positive":"danger"}/></div>{health.data?.ok&&<div className="mt-3 grid gap-2 text-sm"><div className="money-line"><span>Database</span><b>{String((health.data as any).database||"—")}</b></div><div className="money-line"><span>Schema</span><b>{String((health.data as any).schema||"—")}</b></div><div className="money-line"><span>Versão schema</span><b>{String((health.data as any).schema_version||"—")}</b></div><div className="money-line"><span>PostgreSQL</span><b>{String((health.data as any).postgres_version||"—")}</b></div><div className="money-line"><span>Última resposta</span><b>{dateTimePt(String((health.data as any).time||""))}</b></div></div>}
      </SectionPanel>
      <SectionPanel title="Catálogo de serviços" subtitle="Serviços disponíveis ao montar um orçamento/atendimento" icon={Wrench}>
        <div className="mb-3 flex justify-end"><ServiceDialog categories={settings.data?.serviceCategories??[]} onDone={refreshCatalog}/></div><div className="space-y-2">{services.data?.items.map(s=><div className="record-card" key={s.id}><div><b>{s.name}</b><span>{s.category||"Sem categoria"} • Venda {brl(asNumber(s.defaultPrice))} • Custo {brl(asNumber(s.defaultCost))}</span></div><ServiceDialog service={s} categories={settings.data?.serviceCategories??[]} onDone={refreshCatalog}/></div>)}{!services.isLoading&&(services.data?.items.length??0)===0&&<p className="py-5 text-center text-sm text-muted-foreground">Cadastre os serviços usados nos atendimentos.</p>}</div>
      </SectionPanel>
      <SectionPanel title="Usuários e permissões" subtitle={isAdmin?"Usuários autenticados no PostgreSQL":"Somente administradores podem gerenciar usuários"} icon={UserCog}>
        {isAdmin&&<div className="mb-3 flex justify-end"><UserDialog onDone={refreshUsers}/></div>}<div className="space-y-2">{users.data?.items.map(u=><div className="record-card" key={u.id}><div><b>{u.displayName}</b><span>@{u.username} • {String(u.role).toLowerCase()==="admin"?"Administrador":"Operador"}{u.active===false?" • Inativo":""}</span></div><div className="flex items-center gap-2"><StatusPill label={u.active===false?"Inativo":"Ativo"} tone={u.active===false?"danger":"positive"}/><UserDialog user={u} onDone={refreshUsers}/></div></div>)}{!isAdmin&&<p className="py-5 text-sm text-muted-foreground">Entre com um usuário administrador para acessar esta seção.</p>}</div>
      </SectionPanel>
    </div>
  </InternalPage>
}

function ServiceDialog({service,categories,onDone}:{service?:ServiceApi;categories:Array<{id:string;name:string}>;onDone:()=>Promise<void>|void}){
  const [open,setOpen]=useState(false);const [form,setForm]=useState({name:service?.name||"",description:service?.description||"",categoryId:service?.categoryId||"",defaultPrice:String(service?.defaultPrice??0),defaultCost:String(service?.defaultCost??0)});useEffect(()=>{if(open)setForm({name:service?.name||"",description:service?.description||"",categoryId:service?.categoryId||"",defaultPrice:String(service?.defaultPrice??0),defaultCost:String(service?.defaultCost??0)})},[open,service?.id]);
  const mutation=useMutation({mutationFn:()=>service?jaguarApi.catalog.updateService({id:service.id,...form}):jaguarApi.catalog.createService(form),onSuccess:async()=>{toast.success(service?"Serviço atualizado.":"Serviço cadastrado.");setOpen(false);await onDone()},onError:e=>toast.error(e.message)});
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{service?<Button variant="ghost" size="sm"><Pencil className="h-4 w-4"/></Button>:<Button size="sm"><Plus className="mr-2 h-4 w-4"/>Novo serviço</Button>}</DialogTrigger><DialogContent><form onSubmit={e=>{e.preventDefault();mutation.mutate()}}><DialogHeader><DialogTitle>{service?"Editar serviço":"Novo serviço"}</DialogTitle><DialogDescription>Preço padrão pode ser alterado individualmente no orçamento.</DialogDescription></DialogHeader><div className="grid gap-4 py-4"><Field label="Nome"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Categoria"><select className="h-10 rounded-md border border-input bg-background px-3" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Sem categoria</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Descrição"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Preço padrão"><Input type="number" min="0" step="0.01" value={form.defaultPrice} onChange={e=>setForm({...form,defaultPrice:e.target.value})}/></Field><Field label="Custo padrão"><Input type="number" min="0" step="0.01" value={form.defaultCost} onChange={e=>setForm({...form,defaultCost:e.target.value})}/></Field></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={mutation.isPending}>Salvar</Button></DialogFooter></form></DialogContent></Dialog>
}

function UserDialog({user,onDone}:{user?:ApiUser;onDone:()=>Promise<void>|void}){
  const [open,setOpen]=useState(false);const [form,setForm]=useState({username:user?.username||"",displayName:user?.displayName||"",email:user?.email||"",role:String(user?.role||"operator").toLowerCase(),active:user?.active!==false,password:"",mustChangePassword:user?.mustChangePassword??!user});useEffect(()=>{if(open)setForm({username:user?.username||"",displayName:user?.displayName||"",email:user?.email||"",role:String(user?.role||"operator").toLowerCase(),active:user?.active!==false,password:"",mustChangePassword:user?.mustChangePassword??!user})},[open,user?.id]);
  const mutation=useMutation({mutationFn:()=>user?jaguarApi.settings.updateUser({id:user.id,...form,password:form.password||undefined}):jaguarApi.settings.createUser(form),onSuccess:async()=>{toast.success(user?"Usuário atualizado.":"Usuário criado.");setOpen(false);await onDone()},onError:e=>toast.error(e.message)});
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{user?<Button variant="outline" size="sm">Editar</Button>:<Button size="sm"><Plus className="mr-2 h-4 w-4"/>Novo usuário</Button>}</DialogTrigger><DialogContent><form onSubmit={e=>{e.preventDefault();mutation.mutate()}}><DialogHeader><DialogTitle>{user?"Editar usuário":"Novo usuário"}</DialogTitle><DialogDescription>A senha é armazenada com bcrypt/pgcrypto; operadores não gerenciam usuários.</DialogDescription></DialogHeader><div className="grid gap-4 py-4 sm:grid-cols-2"><Field label="Usuário"><Input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Field><Field label="Nome"><Input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></Field><Field label="E-mail"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Perfil"><select className="h-10 rounded-md border border-input bg-background px-3" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="operator">Operador</option><option value="admin">Administrador</option></select></Field><Field label={user?"Nova senha (opcional)":"Senha inicial"}><Input required={!user} type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field><label className="form-field"><span>Ativo</span><div className="flex h-10 items-center"><Switch checked={form.active} onCheckedChange={v=>setForm({...form,active:v})}/></div></label><label className="form-field sm:col-span-2"><span>Exigir troca de senha no próximo acesso</span><div className="flex h-10 items-center gap-2"><Switch checked={form.mustChangePassword} onCheckedChange={v=>setForm({...form,mustChangePassword:v})}/><span className="text-xs text-muted-foreground">Recomendado ao criar usuário.</span></div></label></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={mutation.isPending}>Salvar usuário</Button></DialogFooter></form></DialogContent></Dialog>
}

function fromCompany(c:any):CompanyForm{return {businessName:c.business_name??c.businessName??"Jaguar Radiadores",tradeName:c.trade_name??c.tradeName??"Jaguar Radiadores",cnpj:c.cnpj??"",stateRegistration:c.state_registration??c.stateRegistration??"",phone:c.phone??"",whatsapp:c.whatsapp??"",email:c.email??"",street:c.street??"",number:c.number??"",complement:c.complement??"",neighborhood:c.neighborhood??"",city:c.city??"",state:c.state??"PR",postalCode:c.postal_code??c.postalCode??"",pixKeyType:c.pix_key_type??c.pixKeyType??"cnpj",pixKey:c.pix_key??c.pixKey??"",pixReceiverName:c.pix_receiver_name??c.pixReceiverName??"Jaguar Radiadores",pixReceiverCity:c.pix_receiver_city??c.pixReceiverCity??"",reserveStockOnQuote:c.reserve_stock_on_quote??c.reserveStockOnQuote??true,consumeStockOnComplete:c.consume_stock_on_complete??c.consumeStockOnComplete??true,defaultAuthorizationMethod:c.default_authorization_method??c.defaultAuthorizationMethod??"verbal"}}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>}
