import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Check, ChevronLeft, ChevronRight, CircleDollarSign, FileText, PackagePlus, Plus, Search, Trash2, UserRound, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { InternalPage, StatusPill } from "@/components/InternalPage";
import { PageHeader } from "@/components/ui-helpers";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { jaguarApi } from "@/services/jaguarApi";
import { silentInvalidate } from "@/utils/query-sync";
import { brl } from "@/utils/format";
import { asNumber, paymentMethodLabel } from "@/utils/api-format";
import { buildSchedule, paymentTermsFromSchedule, splitAmounts, type ScheduleItem, type ScheduleMode } from "@/utils/payment-schedule";

export const Route = createFileRoute("/orcamentos_/novo")({ component: NewQuotePage });
const stepLabels = ["Cliente", "Veículo", "Itens", "Pagamento", "Revisão"];
type DraftItem = { id:string; typeCode:"service"|"product"; serviceId?:string; productId?:string; description:string; quantity:number; unitPrice:number; stockAvailable?:number; reserveStock?:boolean };

function today(){ return new Date().toISOString().slice(0,10); }
function nextMonth15(){ const d=new Date(); d.setMonth(d.getMonth()+1); d.setDate(15); return d.toISOString().slice(0,10); }

function NewQuotePage(){
  const qc=useQueryClient();
  const navigate=useNavigate();
  const clientsQ=useQuery({queryKey:["clients","quote"],queryFn:()=>jaguarApi.clients.list({limit:200})});
  const catalogQ=useQuery({queryKey:["catalog"],queryFn:()=>jaguarApi.catalog.all()});
  const [step,setStep]=useState(0); const [customerSearch,setCustomerSearch]=useState("");
  const clients=clientsQ.data?.items??[]; const catalog=catalogQ.data;
  const [customerId,setCustomerId]=useState("");
  const effectiveCustomerId=customerId || clients[0]?.id || "";
  const customerQ=useQuery({queryKey:["client",effectiveCustomerId],queryFn:()=>jaguarApi.clients.detail(effectiveCustomerId),enabled:Boolean(effectiveCustomerId)});
  const customer=customerQ.data?.customer; const [vehicleId,setVehicleId]=useState("");
  const vehicle=customer?.vehicles.find(v=>v.id===vehicleId) ?? customer?.vehicles[0];
  const [items,setItems]=useState<DraftItem[]>([]); const [discount,setDiscount]=useState(0);
  const [payment,setPayment]=useState("pix"); const [approval,setApproval]=useState("verbal"); const [notes,setNotes]=useState("");
  const [entryAmount,setEntryAmount]=useState(0); const [installmentsCount,setInstallmentsCount]=useState(2); const [firstDueDate,setFirstDueDate]=useState(nextMonth15()); const [dueDay,setDueDay]=useState(15);
  const [scheduleMode,setScheduleMode]=useState<ScheduleMode>("monthly"); const [intervalDays,setIntervalDays]=useState(30); const [customSchedule,setCustomSchedule]=useState<ScheduleItem[]>([]); const [receivedNow,setReceivedNow]=useState(false); const [receivedMethod,setReceivedMethod]=useState("pix");
  const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.quantity*i.unitPrice,0),[items]); const total=Math.max(0,subtotal-discount);
  const filteredClients=clients.filter(c=>`${c.name} ${c.phone??""} ${c.document??""}`.toLowerCase().includes(customerSearch.toLowerCase())).slice(0,8);
  const schedule=useMemo(()=>payment==="credit_agreement"?buildSchedule({total,entryAmount,installmentsCount,firstDueDate,dueDay,mode:scheduleMode,intervalDays,custom:customSchedule,entryDueDate:today()}):buildSchedule({total,entryAmount:0,installmentsCount:1,firstDueDate:today(),dueDay:new Date().getDate(),mode:"monthly"}),[payment,total,entryAmount,installmentsCount,firstDueDate,dueDay,scheduleMode,intervalDays,customSchedule]);
  const paymentTerms=useMemo(()=>payment==="credit_agreement"?paymentTermsFromSchedule({methodCode:payment,mode:scheduleMode,entryAmount,entryDueDate:today(),installmentsCount,firstDueDate,dueDay,intervalDays,custom:customSchedule,total}):{methodCode:payment,installmentsCount:1,firstDueDate:today(),dueDay:new Date().getDate()},[payment,scheduleMode,entryAmount,installmentsCount,firstDueDate,dueDay,intervalDays,customSchedule,total]);
  const create=useMutation({mutationFn:()=>jaguarApi.quotes.create({customerId:effectiveCustomerId,vehicleId:vehicle?.id||null,issueReported:notes,authorizationMethod:approval,items:items.map((i,index)=>({typeCode:i.typeCode,productId:i.productId,serviceId:i.serviceId,description:i.description,quantity:i.quantity,unitPrice:i.unitPrice,reserveStock:i.typeCode==="product"?i.reserveStock!==false:false,sortOrder:index})),discountType:discount>0?"amount":"none",discountValue:discount,paymentTerms,notes}),onSuccess:async(r)=>{toast.success("Orçamento/atendimento criado.");if(receivedNow){const target=r.quote.receivables?.[0];if(target&&asNumber(target.balance)>0){try{await jaguarApi.finance.receive({receivableId:target.id,amount:payment==="credit_agreement"&&entryAmount>0?Math.min(entryAmount,asNumber(target.balance)):asNumber(target.balance),paymentDate:today(),paymentMethodCode:receivedMethod});toast.success(payment==="credit_agreement"&&entryAmount>0?"Entrada registrada como recebida.":"Pagamento registrado como recebido.");}catch(e:any){toast.error(`Orçamento criado, mas o recebimento não foi registrado: ${e.message}`);}}}qc.setQueryData(["quote",r.quote.id],r);silentInvalidate(qc,[["quotes"],["dashboard"],["receivables"],["cashflow"],["reports"],["products"]]);await navigate({to:"/orcamentos/$orcamentoId",params:{orcamentoId:r.quote.id}});},onError:e=>toast.error(e.message)});
  function prepareCustomSchedule(){const remaining=Math.max(0,total-entryAmount);const amounts=splitAmounts(remaining,Math.max(1,installmentsCount));const base=buildSchedule({total,entryAmount,installmentsCount,firstDueDate,dueDay,mode:"monthly",entryDueDate:today()}).installments;setCustomSchedule(base.map((x,i)=>({number:i+1,dueDate:x.dueDate,amount:amounts[i]??0})));setScheduleMode("custom");}
  function addService(){setItems(l=>[...l,{id:crypto.randomUUID(),typeCode:"service",description:"Serviço",quantity:1,unitPrice:0}]);}
  function addPart(){if(catalogQ.isLoading)return toast.info("O catálogo ainda está carregando.");const p=catalog?.products[0]; if(!p)return toast.error("Cadastre ao menos um produto no estoque."); setItems(l=>[...l,{id:crypto.randomUUID(),typeCode:"product",productId:p.id,description:p.description,quantity:1,unitPrice:asNumber(p.salePrice),stockAvailable:asNumber(p.available),reserveStock:true}]);}
  function changeCatalogItem(id:string,newId:string,type:"service"|"product") { if(type==="service"){if(!newId){setItems(l=>l.map(i=>i.id===id?{...i,serviceId:undefined,description:i.description||"Serviço",unitPrice:i.unitPrice||0}:i));return;}const s=catalog?.services.find(x=>x.id===newId);if(s)setItems(l=>l.map(i=>i.id===id?{...i,serviceId:s.id,description:s.name,unitPrice:asNumber(s.defaultPrice)}:i));} else {const p=catalog?.products.find(x=>x.id===newId);if(p)setItems(l=>l.map(i=>i.id===id?{...i,productId:p.id,description:p.description,unitPrice:asNumber(p.salePrice),stockAvailable:asNumber(p.available)}:i));}}
  if(clientsQ.isLoading)return <InternalPage><div className="panel p-8 text-muted-foreground">Carregando clientes...</div></InternalPage>;
  return <InternalPage>
    <PageHeader title="Novo Orçamento / Atendimento" subtitle="Crie o atendimento real; peças podem ser reservadas e o financeiro é gerado automaticamente." icon={FileText}/>
    <div className="quote-stepper">{stepLabels.map((label,index)=><div key={label} className={`quote-step ${index===step?"is-active":""} ${index<step?"is-done":""}`}><span>{index<step?<Check className="h-3.5 w-3.5"/>:index+1}</span><b>{label}</b></div>)}</div>
    <section className="panel quote-workspace">
      {step===0&&<div className="quote-step-content"><StepTitle icon={UserRound} title="Dados do cliente" subtitle="Selecione um cliente cadastrado."/><div className="relative max-w-2xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Buscar por nome, telefone ou CPF/CNPJ..."/></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredClients.map(c=><button key={c.id} className={`select-card ${effectiveCustomerId===c.id?"is-selected":""}`} onClick={()=>{setCustomerId(c.id);setVehicleId("");}}><div><b>{c.name}</b><span>{c.document||"Sem documento"}</span></div><small>{c.phone||"Sem telefone"}</small></button>)}</div>{customer&&<div className="form-grid"><label className="form-field"><span>Cliente</span><Input value={customer.kind==="PJ"?"Pessoa Jurídica":"Pessoa Física"} readOnly/></label><label className="form-field"><span>CPF / CNPJ</span><Input value={customer.document??""} readOnly/></label><label className="form-field"><span>Inscrição</span><Input value={customer.registration??""} readOnly/></label><label className="form-field"><span>Telefone</span><Input value={customer.phone??""} readOnly/></label><label className="form-field"><span>Responsável</span><Input value={customer.responsible??""} readOnly/></label><label className="form-field xl:col-span-2"><span>Endereço</span><Input value={`${customer.address??""}${customer.city?`, ${customer.city} - ${customer.state??""}`:""}`} readOnly/></label></div>}</div>}
      {step===1&&<div className="quote-step-content"><StepTitle icon={Wrench} title="Dados do veículo / equipamento" subtitle="Selecione um veículo/equipamento vinculado ao cliente."/>{customer?.vehicles.length?<div className="grid gap-3 md:grid-cols-2">{customer.vehicles.map(v=><button key={v.id} className={`select-card ${(vehicle?.id===v.id)?"is-selected":""}`} onClick={()=>setVehicleId(v.id)}><div><b>{[v.brand,v.model].filter(Boolean).join(" ")||v.type||"Veículo/equipamento"}</b><span>{v.plate||"Sem placa"}</span></div><small>{v.type||""}</small></button>)}</div>:<div className="panel p-4 text-sm text-muted-foreground">Este cliente não possui veículo/equipamento. Você pode continuar sem vínculo ou cadastrá-lo na tela do cliente.</div>}<div className="form-grid"><label className="form-field"><span>Placa</span><Input value={vehicle?.plate??""} readOnly/></label><label className="form-field"><span>Marca</span><Input value={vehicle?.brand??""} readOnly/></label><label className="form-field"><span>Modelo</span><Input value={vehicle?.model??""} readOnly/></label><label className="form-field xl:col-span-3"><span>Problema relatado / observações</span><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ex.: Radiador com vazamento na parte superior."/></label></div></div>}
      {step===2&&<div className="quote-step-content"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><StepTitle icon={PackagePlus} title="Peças e serviços" subtitle="Selecione itens reais do catálogo; peças podem reservar estoque."/><div className="flex gap-2"><Button variant="outline" onClick={addService}><Plus className="mr-2 h-4 w-4"/>Adicionar serviço</Button><Button onClick={addPart}><Plus className="mr-2 h-4 w-4"/>Adicionar peça</Button></div></div><div className="data-table-wrap border"><table className="data-table quote-items-table min-w-[900px]"><thead><tr><th>Tipo</th><th>Catálogo</th><th>Descrição</th><th>Qtd.</th><th>Valor unit.</th><th>Total</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><StatusPill label={item.typeCode==="product"?"Peça":"Serviço"} tone={item.typeCode==="product"?"warning":"info"}/></td><td>{item.typeCode==="product"?<select className="h-9 rounded-md border bg-background px-2 text-sm" value={item.productId} onChange={e=>changeCatalogItem(item.id,e.target.value,"product")}>{catalog?.products.map(p=><option key={p.id} value={p.id}>{p.code?`${p.code} · `:""}{p.description}</option>)}</select>:<select className="h-9 rounded-md border bg-background px-2 text-sm" value={item.serviceId??""} onChange={e=>changeCatalogItem(item.id,e.target.value,"service")}><option value="">Serviço livre / descrição manual</option>{catalog?.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</td><td><Input value={item.description} onChange={e=>setItems(l=>l.map(i=>i.id===item.id?{...i,description:e.target.value}:i))}/>{item.stockAvailable!=null&&<small className="mt-1 block text-muted-foreground">Disponível: {item.stockAvailable}</small>}</td><td><Input type="number" min={0.01} step="0.01" value={item.quantity} onChange={e=>setItems(l=>l.map(i=>i.id===item.id?{...i,quantity:Number(e.target.value)}:i))}/></td><td><Input type="number" min={0} step="0.01" value={item.unitPrice} onChange={e=>setItems(l=>l.map(i=>i.id===item.id?{...i,unitPrice:Number(e.target.value)}:i))}/></td><td className="font-semibold">{brl(item.quantity*item.unitPrice)}</td><td><Button variant="ghost" size="icon" className="text-destructive" onClick={()=>setItems(l=>l.filter(i=>i.id!==item.id))}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table></div><div className="quote-totals"><div><span>Subtotal</span><b>{brl(subtotal)}</b></div><div><span>Desconto</span><Input type="number" min={0} step="0.01" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></div><div className="is-total"><span>Total geral</span><b>{brl(total)}</b></div></div></div>}
      {step===3&&<div className="quote-step-content">
        <StepTitle icon={CircleDollarSign} title="Pagamento" subtitle="À vista ou a prazo na confiança, com parcelas e vencimentos combinados."/>
        <div className="grid gap-4 xl:grid-cols-[.9fr_1.1fr]">
          <div className="option-panel">
            <h3>Forma de pagamento</h3>
            <RadioGroup value={payment} onValueChange={v=>{setPayment(v);setReceivedNow(false)}} className="mt-4 space-y-3">{(catalog?.paymentMethods??[]).map(p=><label key={p.code} className="radio-line"><RadioGroupItem value={p.code}/><span>{p.name}</span></label>)}</RadioGroup>
            <div className="mt-5"><span className="form-label">Autorização do cliente</span><div className="segmented-control mt-2 flex-wrap">{[{c:"verbal",l:"Verbal"},{c:"whatsapp",l:"WhatsApp"},{c:"signature",l:"Assinatura"},{c:"other",l:"Outro"}].map(a=><button type="button" key={a.c} className={approval===a.c?"is-active":""} onClick={()=>setApproval(a.c)}>{a.l}</button>)}</div></div>
          </div>
          <div className="option-panel">
            <div className="flex flex-wrap items-start justify-between gap-2"><div><h3>Condição</h3><p className="mt-1 text-xs text-muted-foreground">Total do atendimento: <b>{brl(total)}</b></p></div>{payment==="credit_agreement"&&<div className="segmented-control flex-wrap"><button type="button" className={scheduleMode==="monthly"?"is-active":""} onClick={()=>setScheduleMode("monthly")}>Todo mês</button><button type="button" className={scheduleMode==="interval"?"is-active":""} onClick={()=>setScheduleMode("interval")}>Intervalo</button><button type="button" className={scheduleMode==="custom"?"is-active":""} onClick={prepareCustomSchedule}>Datas livres</button></div>}</div>
            {payment==="credit_agreement"?<>
              <div className="form-grid mt-4"><label className="form-field"><span>Entrada</span><Input type="number" min={0} max={total} step="0.01" value={entryAmount} onChange={e=>setEntryAmount(Number(e.target.value))}/></label><label className="form-field"><span>Parcelas após entrada</span><Input type="number" min={1} max={36} value={installmentsCount} onChange={e=>setInstallmentsCount(Number(e.target.value))}/></label><label className="form-field"><span>1º vencimento</span><Input type="date" value={firstDueDate} onChange={e=>setFirstDueDate(e.target.value)}/></label>{scheduleMode==="monthly"&&<label className="form-field"><span>Dia fixo dos próximos vencimentos</span><Input type="number" min={1} max={31} value={dueDay} onChange={e=>setDueDay(Number(e.target.value))}/></label>}{scheduleMode==="interval"&&<label className="form-field"><span>Intervalo entre parcelas (dias)</span><Input type="number" min={1} max={365} value={intervalDays} onChange={e=>setIntervalDays(Number(e.target.value))}/></label>}</div>
              {scheduleMode==="custom"&&<div className="mt-4 space-y-2"><div className="flex items-center justify-between"><span className="form-label">Datas e valores personalizados</span><Button type="button" size="sm" variant="outline" onClick={prepareCustomSchedule}>Recalcular parcelas</Button></div>{customSchedule.map((r,i)=><div key={i} className="grid grid-cols-[52px_1fr_1fr] items-center gap-2"><b className="text-sm">{i+1}/{customSchedule.length}</b><Input type="date" value={r.dueDate} onChange={e=>setCustomSchedule(rows=>rows.map((x,j)=>j===i?{...x,dueDate:e.target.value}:x))}/><Input type="number" min="0.01" step="0.01" value={r.amount} onChange={e=>setCustomSchedule(rows=>rows.map((x,j)=>j===i?{...x,amount:Number(e.target.value)}:x))}/></div>)}</div>}
              <div className="mt-4 rounded-xl border p-4"><div className="mb-2 flex items-center justify-between"><b className="text-sm">Previsão das parcelas</b><span className="text-xs text-muted-foreground">Atraso calculado automaticamente</span></div>{schedule.entry&&<div className="review-line"><span>Entrada · {new Date(`${schedule.entry.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}</span><b>{brl(schedule.entry.amount)}</b></div>}{schedule.installments.map(r=><div className="review-line" key={`${r.number}-${r.dueDate}`}><span>{r.number}/{schedule.installments.length} · {new Date(`${r.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}</span><b>{brl(r.amount)}</b></div>)}</div>
              {entryAmount>0&&<label className="mt-4 flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={receivedNow} onChange={e=>setReceivedNow(e.target.checked)}/><span><b>Entrada já recebida agora</b><small className="mt-0.5 block text-muted-foreground">Ao criar o orçamento, a entrada será baixada automaticamente.</small></span></label>}
            </>:<>
              <div className="mt-4 rounded-xl border p-4 text-sm text-muted-foreground">Será criada uma cobrança de <b className="text-foreground">{brl(total)}</b> com vencimento hoje. Você pode marcar como recebida agora ou deixar em aberto.</div>
              <label className="mt-4 flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={receivedNow} onChange={e=>setReceivedNow(e.target.checked)}/><span><b>Pagamento já recebido</b><small className="mt-0.5 block text-muted-foreground">Útil para PIX, dinheiro, débito ou cartão recebidos no atendimento.</small></span></label>
            </>}
            {receivedNow&&<label className="form-field mt-4"><span>Forma realmente recebida</span><select className="h-10 rounded-md border bg-background px-3" value={receivedMethod} onChange={e=>setReceivedMethod(e.target.value)}>{(catalog?.paymentMethods??[]).filter(m=>m.code!=="credit_agreement").map(m=><option key={m.code} value={m.code}>{m.name}</option>)}</select></label>}
          </div>
        </div>
      </div>}
      {step===4&&<div className="quote-step-content"><StepTitle icon={Check} title="Revisão" subtitle="Confira antes de criar o atendimento e suas cobranças."/><div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-4"><div className="review-card"><h3>Cliente</h3><p><b>{customer?.name}</b></p><span>{customer?.document} · {customer?.phone}</span></div><div className="review-card"><h3>Veículo / equipamento</h3><p><b>{[vehicle?.brand,vehicle?.model].filter(Boolean).join(" ")||vehicle?.type||"Sem vínculo"}</b></p><span>{vehicle?.plate?`Placa ${vehicle.plate}`:"Sem placa"}</span><span>{notes}</span></div><div className="review-card"><h3>Itens</h3>{items.map(item=><div key={item.id} className="review-line"><span>{item.quantity}× {item.description}</span><b>{brl(item.quantity*item.unitPrice)}</b></div>)}</div></div><div className="review-summary"><div><span>Subtotal</span><b>{brl(subtotal)}</b></div><div><span>Desconto</span><b>{brl(discount)}</b></div><div className="is-total"><span>Total geral</span><b>{brl(total)}</b></div><hr/><div><span>Pagamento</span><b>{paymentMethodLabel(payment,catalog?.paymentMethods)}</b></div>{payment==="credit_agreement"&&<div><span>Parcelamento</span><b>{schedule.installments.length} parcela(s){entryAmount>0?` + entrada ${brl(entryAmount)}`:""}</b></div>}{receivedNow&&<div><span>Recebimento inicial</span><b>{payment==="credit_agreement"&&entryAmount>0?`Entrada de ${brl(entryAmount)} já recebida`:"Pagamento recebido"}</b></div>}<div><span>Status inicial</span><b>Em andamento</b></div><div className="mt-4"><Button className="w-full" disabled={create.isPending||!effectiveCustomerId||items.length===0} onClick={()=>create.mutate()}>{create.isPending?"Criando atendimento...":"Criar e iniciar atendimento"}</Button></div></div></div></div>}
      <div className="quote-actions"><Button asChild variant="ghost"><Link to="/orcamentos">Cancelar</Link></Button><div className="flex gap-2">{step>0&&<Button variant="outline" onClick={()=>setStep(v=>Math.max(0,v-1))}><ChevronLeft className="mr-1 h-4 w-4"/>Voltar</Button>}{step<4&&<Button onClick={()=>setStep(v=>Math.min(4,v+1))} disabled={(step===0&&!effectiveCustomerId)||(step===2&&!items.length)}>Próximo<ChevronRight className="ml-1 h-4 w-4"/></Button>}</div></div>
    </section>
  </InternalPage>;
}
function StepTitle({icon:Icon,title,subtitle}:{icon:typeof UserRound;title:string;subtitle:string}){return <div className="step-title"><span><Icon className="h-5 w-5"/></span><div><h2>{title}</h2><p>{subtitle}</p></div></div>}
