/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos_.novo'
import { Route as OrcamentosOrcamentoIdRouteImport } from './routes/orcamentos_.$orcamentoId'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes_.$clienteId'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/orcamentos_/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosOrcamentoIdRoute = OrcamentosOrcamentoIdRouteImport.update({
  id: '/orcamentos_/$orcamentoId',
  path: '/orcamentos/$orcamentoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes_/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/orcamentos/$orcamentoId': typeof OrcamentosOrcamentoIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/orcamentos/$orcamentoId': typeof OrcamentosOrcamentoIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes_/$clienteId': typeof ClientesClienteIdRoute
  '/orcamentos_/$orcamentoId': typeof OrcamentosOrcamentoIdRoute
  '/orcamentos_/novo': typeof OrcamentosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/login'
    | '/orcamentos'
    | '/relatorios'
    | '/clientes/$clienteId'
    | '/orcamentos/$orcamentoId'
    | '/orcamentos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/login'
    | '/orcamentos'
    | '/relatorios'
    | '/clientes/$clienteId'
    | '/orcamentos/$orcamentoId'
    | '/orcamentos/novo'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/login'
    | '/orcamentos'
    | '/relatorios'
    | '/clientes_/$clienteId'
    | '/orcamentos_/$orcamentoId'
    | '/orcamentos_/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FornecedoresRoute: typeof FornecedoresRoute
  LoginRoute: typeof LoginRoute
  OrcamentosRoute: typeof OrcamentosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  OrcamentosOrcamentoIdRoute: typeof OrcamentosOrcamentoIdRoute
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos_/novo': {
      id: '/orcamentos_/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos_/$orcamentoId': {
      id: '/orcamentos_/$orcamentoId'
      path: '/orcamentos/$orcamentoId'
      fullPath: '/orcamentos/$orcamentoId'
      preLoaderRoute: typeof OrcamentosOrcamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/$clienteId': {
      id: '/clientes_/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  FornecedoresRoute: FornecedoresRoute,
  LoginRoute: LoginRoute,
  OrcamentosRoute: OrcamentosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  OrcamentosOrcamentoIdRoute: OrcamentosOrcamentoIdRoute,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
